import readline from 'readline';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (query: string): Promise<string> => {
  return new Promise((resolve) => rl.question(query, resolve));
};

function updateEnvKey(content: string, key: string, value: string): string {
  const lines = content.split(/\r?\n/);
  let keyFound = false;

  const updatedLines = lines.map((line) => {
    const trimmed = line.trim();
    if (trimmed.startsWith(`${key}=`) || trimmed.startsWith(`${key} =`)) {
      keyFound = true;
      return `${key}=${value}`;
    }
    return line;
  });

  if (!keyFound) {
    updatedLines.push(`${key}=${value}`);
  }

  return updatedLines.join('\n');
}

async function main() {
  const envPath = path.join(process.cwd(), '.env');
  if (!fs.existsSync(envPath)) {
    console.error('❌ .env file not found. Please create a .env file first.');
    rl.close();
    process.exit(1);
  }

  let envContent = fs.readFileSync(envPath, 'utf8');

  // 1. Generate secrets
  const jwtSecret = crypto.randomBytes(32).toString('hex');
  const jwtRefreshSecret = crypto.randomBytes(32).toString('hex');

  console.log('Generating secure secrets...');
  
  envContent = updateEnvKey(envContent, 'JWT_SECRET', jwtSecret);
  envContent = updateEnvKey(envContent, 'JWT_REFRESH_SECRET', jwtRefreshSecret);

  // 2. Admin password setup
  console.log('\n--- Admin Password Setup ---');
  let adminPassword = await question('Enter new admin password (or leave empty to generate a random one): ');
  adminPassword = adminPassword.trim();

  let autoGenerated = false;
  if (!adminPassword) {
    adminPassword = crypto.randomBytes(12).toString('base64url'); // safe random password
    autoGenerated = true;
  }

  const adminPasswordHash = await bcrypt.hash(adminPassword, 10);

  envContent = updateEnvKey(envContent, 'ADMIN_PASSWORD_HASH', adminPasswordHash);

  // Write to .env
  fs.writeFileSync(envPath, envContent, 'utf8');

  console.log('\n✅ Secrets updated in .env successfully!');
  console.log(`🔑 JWT_SECRET generated.`);
  console.log(`🔑 JWT_REFRESH_SECRET generated.`);
  
  if (autoGenerated) {
    console.log(`👤 Admin Password (Auto-Generated): \x1b[33m${adminPassword}\x1b[0m`);
    console.log('⚠️  Please save this password securely. It will not be shown again.');
  } else {
    console.log('👤 Admin Password updated and hashed in .env.');
  }
  
  rl.close();
}

main().catch((err) => {
  console.error('An error occurred:', err);
  rl.close();
  process.exit(1);
});
